In [1]:
import numpy as np
import pandas as pd

In [2]:
ds = pd.read_csv("data.csv")

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [4]:
ds["year"].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [5]:
ds['year'] = pd.to_numeric(ds['year'], errors = 'coerce')# first make it numeric
ds = ds.dropna(subset=['year'])#drop nan 
ds['year'] = ds['year'].astype(int) # convert datatype to int(integer) because year cannot be in float

In [7]:
ds["Price"] = ds["Price"].str.replace(",","")
ds["Price"].unique()

array(['80000', '425000', 'Ask For Price', '325000', '575000', '175000',
       '190000', '830000', '250000', '182000', '315000', '415000',
       '320000', '1000000', '500000', '350000', '160000', '310000',
       '75000', '100000', '290000', '95000', '180000', '385000', '105000',
       '650000', '689999', '448000', '549000', '501000', '489999',
       '280000', '349999', '284999', '345000', '499999', '235000',
       '249999', '1475000', '395000', '220000', '170000', '85000',
       '200000', '570000', '110000', '448999', '1891111', '159500',
       '344999', '449999', '865000', '699000', '375000', '224999',
       '1200000', '195000', '351000', '240000', '90000', '155000',
       '600000', '189500', '210000', '390000', '135000', '1600000',
       '701000', '265000', '525000', '372000', '635000', '550000',
       '485000', '329500', '251111', '569999', '69999', '299999',
       '399999', '450000', '270000', '158400', '179000', '125000',
       '299000', '150000', '275000', '285000', '340000', '70000',
       '289999', '849999', '749999', '274999', '984999', '599999',
       '244999', '474999', '245000', '169500', '370000', '168000',
       '145000', '98500', '209000', '185000', '900000', '699999',
       '199999', '544999', '199000', '540000', '49000', '700000', '55000',
       '895000', '355000', '565000', '365000', '40000', '400000',
       '330000', '580000', '379000', '219000', '519000', '730000',
       '2000000', '2100000', '1400000', '311000', '855000', '535000',
       '178000', '300000', '255000', '549999', '380000', '57000',
       '410000', '225000', '120000', '59000', '599000', '675000', '72500',
       '610000', '230000', '520000', '524999', '424999', '644999',
       '584999', '799999', '444999', '649999', '944999', '574999',
       '374999', '130000', '401000', '1350000', '174999', '239999',
       '99999', '324999', '1074999', '1130000', '149000', '770000',
       '30000', '335000', '399000', '65000', '169999', '165000', '560000',
       '950000', '715000', '45000', '940000', '155555', '1500000',
       '495000', '800000', '1299000', '530000', '1499000', '32000',
       '405000', '760000', '750000', '419000', '140000', '1540000',
       '123000', '498000', '480000', '488000', '1525000', '548900',
       '725000', '99000', '52000', '2800000', '499000', '381000',
       '278000', '690000', '260000', '90001', '115000', '1599000',
       '159000', '51999', '215000', '35000', '1150000', '269000', '60000',
       '430000', '8500003', '401919', '490000', '424000', '205000',
       '549900', '435000', '189700', '389700', '360000', '295000',
       '114990', '1065000', '470000', '48000', '188000', '465000',
       '179999', '2190000', '2390000', '1075000', '475000', '1025000',
       '615000', '1900000', '1490000', '1510000', '1850000', '790000',
       '1725000', '1225000', '68000', '970000', '3100000', '899000',
       '88000', '53000', '568500', '71000', '590000', '795000', '42000',
       '189000', '162000', '35999', '2900000', '39999', '50500', '510000',
       '860000', '500001'], dtype=object)

In [15]:
ds["Price"] = pd.to_numeric(ds["Price"] , errors = 'coerce')

In [16]:
ds["Price"].unique()

array([  80000.,  425000.,      nan,  325000.,  575000.,  175000.,
        190000.,  830000.,  250000.,  182000.,  315000.,  415000.,
        320000., 1000000.,  500000.,  350000.,  160000.,  310000.,
         75000.,  100000.,  290000.,   95000.,  180000.,  385000.,
        105000.,  650000.,  689999.,  448000.,  549000.,  501000.,
        489999.,  280000.,  349999.,  284999.,  345000.,  499999.,
        235000.,  249999., 1475000.,  395000.,  220000.,  170000.,
         85000.,  200000.,  570000.,  110000.,  448999., 1891111.,
        159500.,  344999.,  449999.,  865000.,  699000.,  375000.,
        224999., 1200000.,  195000.,  351000.,  240000.,   90000.,
        155000.,  600000.,  189500.,  210000.,  390000.,  135000.,
       1600000.,  701000.,  265000.,  525000.,  372000.,  635000.,
        550000.,  485000.,  329500.,  251111.,  569999.,   69999.,
        299999.,  399999.,  450000.,  270000.,  158400.,  179000.,
        125000.,  299000.,  150000.,  275000.,  285000.,  340000.,
         70000.,  289999.,  849999.,  749999.,  274999.,  984999.,
        599999.,  244999.,  474999.,  245000.,  169500.,  370000.,
        168000.,  145000.,   98500.,  209000.,  185000.,  900000.,
        699999.,  199999.,  544999.,  199000.,  540000.,   49000.,
        700000.,   55000.,  895000.,  355000.,  565000.,  365000.,
         40000.,  400000.,  330000.,  580000.,  379000.,  219000.,
        519000.,  730000., 2000000., 2100000., 1400000.,  311000.,
        855000.,  535000.,  178000.,  300000.,  255000.,  549999.,
        380000.,   57000.,  410000.,  225000.,  120000.,   59000.,
        599000.,  675000.,   72500.,  610000.,  230000.,  520000.,
        524999.,  424999.,  644999.,  584999.,  799999.,  444999.,
        649999.,  944999.,  574999.,  374999.,  130000.,  401000.,
       1350000.,  174999.,  239999.,   99999.,  324999., 1074999.,
       1130000.,  149000.,  770000.,   30000.,  335000.,  399000.,
         65000.,  169999.,  165000.,  560000.,  950000.,  715000.,
         45000.,  940000.,  155555., 1500000.,  495000.,  800000.,
       1299000.,  530000., 1499000.,   32000.,  405000.,  760000.,
        750000.,  419000.,  140000., 1540000.,  123000.,  498000.,
        480000.,  488000., 1525000.,  548900.,  725000.,   99000.,
         52000., 2800000.,  499000.,  381000.,  278000.,  690000.,
        260000.,   90001.,  115000., 1599000.,  159000.,   51999.,
        215000.,   35000., 1150000.,  269000.,   60000.,  430000.,
       8500003.,  401919.,  490000.,  424000.,  205000.,  549900.,
        435000.,  189700.,  389700.,  360000.,  295000.,  114990.,
       1065000.,  470000.,   48000.,  188000.,  465000.,  179999.,
       2190000., 2390000., 1075000.,  475000., 1025000.,  615000.,
       1900000., 1490000., 1510000., 1850000.,  790000., 1725000.,
       1225000.,   68000.,  970000., 3100000.,  899000.,   88000.,
         53000.,  568500.,   71000.,  590000.,  795000.,   42000.,
        189000.,  162000.,   35999., 2900000.,   39999.,   50500.,
        510000.,  860000.,  500001.])

In [17]:
ds.dropna(inplace=True)

In [18]:
ds["kms_driven"] = ds["kms_driven"].str.replace(",","")
ds["kms_driven"] = ds["kms_driven"].str.replace(" kms","")
ds["kms_driven"].unique()

array(['45000', '40', '28000', '36000', '41000', '25000', '24530',
       '60000', '30000', '32000', '48660', '4000', '16934', '43000',
       '35550', '39522', '39000', '55000', '72000', '15975', '70000',
       '23452', '35522', '48508', '15487', '82000', '20000', '68000',
       '38000', '27000', '33000', '46000', '16000', '47000', '35000',
       '30874', '15000', '29685', '130000', '19000', '54000', '13000',
       '38200', '22000', '50000', '13500', '3600', '45863', '60500',
       '12500', '18000', '13349', '29000', '44000', '42000', '14000',
       '49000', '36200', '51000', '104000', '33333', '33600', '5600',
       '7500', '24330', '65480', '200000', '59000', '99000', '2800',
       '21000', '11000', '66000', '3000', '7000', '38500', '37200',
       '43200', '24800', '45872', '40000', '11400', '97200', '52000',
       '31000', '175430', '37000', '65000', '3350', '75000', '62000',
       '73000', '2200', '54870', '34580', '97000', '60', '80200', '3200',
       '0000', '5000', '588', '71200', '175400', '9300', '56758', '10000',
       '56450', '56000', '32700', '9000', '73', '160000', '58559',
       '57000', '170000', '80000', '6821', '23000', '34000', '1800',
       '400000', '48000', '90000', '12000', '69900', '166000', '122', '0',
       '36469', '7800', '24695', '15141', '59910', '100000', '4500',
       '129000', '300', '131000', '111111', '59466', '25500', '44005',
       '2110', '43222', '100200', '65', '140000', '103553', '58000',
       '120000', '49800', '100', '81876', '6020', '55700', '18500',
       '53000', '35500', '22134', '1000', '8500', '87000', '6000', '8000',
       '55800', '56400', '72160', '11500', '133000', '2000', '88000',
       '65422', '117000', '150000', '10750', '6800', '9800', '57923',
       '30201', '6200', '37518', '24652', '383', '95000', '3528', '52500',
       '47900', '52800', '195000', '48008', '48247', '9400', '64000',
       '2137', '10544', '147000', '90001', '48006', '74000', '85000',
       '29500', '39700', '67000', '19336', '60105', '45933', '102563',
       '28600', '41800', '116000', '42590', '7400', '54500', '76000',
       '00', '11523', '38600', '95500', '37458', '85960', '12516',
       '30600', '2550', '62500', '69000', '28400', '68485', '3500',
       '85455', '63000', '1600', '77000', '26500', '2875', '13900',
       '1500', '2450', '1625', '33400', '60123', '137495', '91200',
       '146000', '100800', '2100', '2500', '132000'], dtype=object)

In [19]:
ds["kms_driven"] = pd.to_numeric(ds["kms_driven"] , errors = 'coerce')
ds["kms_driven"]

0       45000
1          40
3       28000
4       36000
6       41000
        ...
883     50000
885     30000
886    132000
888     27000
889     40000
Name: kms_driven, Length: 816, dtype: int64

In [20]:
#to remove unreasonable range or new cars
ds = ds[ds["kms_driven"] >= 10000]

In [21]:
# remove extremely overused cars or errors
ds = ds[ds["kms_driven"] <= 200000]

In [22]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 736 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        736 non-null    object
 1   company     736 non-null    object
 2   year        736 non-null    int32
 3   Price       736 non-null    float64
 4   kms_driven  736 non-null    int64
 5   fuel_type   736 non-null    object
dtypes: float64(1), int32(1), int64(1), object(3)
memory usage: 37.4+ KB

In [23]:
ds["fuel_type"].unique()

array(['Petrol', 'Diesel', 'LPG'], dtype=object)

In [24]:
ds["company"].unique()

array(['Hyundai', 'Ford', 'Maruti', 'Skoda', 'Mahindra', 'Audi', 'Toyota',
       'Renault', 'Honda', 'Datsun', 'Mitsubishi', 'Tata', 'Volkswagen',
       'Chevrolet', 'Mini', 'BMW', 'Nissan', 'Hindustan', 'Fiat',
       'Mercedes', 'Land', 'Force', 'Jaguar', 'Volvo'], dtype=object)

In [25]:
ds["name"].unique()

array(['Hyundai Santro Xing XO eRLX Euro III',
       'Hyundai Grand i10 Magna 1.2 Kappa VTVT',
       'Ford EcoSport Titanium 1.5L TDCi', 'Ford Figo', 'Hyundai Eon',
       'Ford EcoSport Ambiente 1.5L TDCi',
       'Maruti Suzuki Alto K10 VXi AMT', 'Skoda Fabia Classic 1.2 MPI',
       'Maruti Suzuki Stingray VXi', 'Hyundai Elite i20 Magna 1.2',
       'Mahindra Scorpio SLE BS IV', 'Audi Q7', 'Mahindra Scorpio S10',
       'Maruti Suzuki Alto 800', 'Maruti Suzuki Alto 800 Vxi',
       'Hyundai i20 Sportz 1.2', 'Maruti Suzuki Alto 800 Lx',
       'Maruti Suzuki Vitara Brezza ZDi', 'Maruti Suzuki Alto LX',
       'Mahindra Bolero DI', 'Maruti Suzuki Swift Dzire ZDi',
       'Mahindra Scorpio S10 4WD', 'Maruti Suzuki Swift Vdi BSIII',
       'Maruti Suzuki Wagon R VXi BS III',
       'Maruti Suzuki Wagon R VXi Minor',
       'Toyota Innova 2.0 G 8 STR BS IV', 'Renault Lodgy 85 PS RXL',
       'Skoda Yeti Ambition 2.0 TDI CR 4x2',
       'Maruti Suzuki Baleno Delta 1.2',
       'Renault Duster 110 PS RxZ Diesel Plus',
       'Renault Duster 85 PS RxE Diesel', 'Honda City 1.5 S MT',
       'Maruti Suzuki Dzire', 'Honda Amaze', 'Honda Amaze 1.5 SX i DTEC',
       'Honda City', 'Datsun Redi GO S', 'Maruti Suzuki SX4 ZXI MT',
       'Mitsubishi Pajero Sport Limited Edition',
       'Maruti Suzuki Swift VXi 1.2 ABS BS IV', 'Honda City ZX CVT',
       'Maruti Suzuki Wagon R LX BS IV', 'Tata Indigo eCS LS CR4 BS IV',
       'Volkswagen Polo Highline Exquisite P', 'Chevrolet Spark LS 1.0',
       'Renault Duster 110PS Diesel RxZ', 'Mini Cooper S 1.6',
       'Skoda Fabia 1.2L Diesel Ambiente', 'Renault Duster',
       'Mahindra Scorpio S4', 'Mahindra Scorpio VLX 2WD BS IV',
       'Mahindra Quanto C8', 'Ford EcoSport', 'Honda Brio',
       'Hyundai i20 Magna', 'Toyota Corolla Altis Diesel D4DG',
       'Hyundai Verna Transform SX VTVT',
       'Toyota Corolla Altis Petrol Ltd', 'Honda City 1.5 EXi New',
       'Skoda Fabia 1.2L Diesel Elegance', 'BMW 3 Series 320i',
       'Maruti Suzuki A Star Lxi', 'Toyota Etios GD',
       'Ford Figo Diesel EXI Option',
       'Maruti Suzuki Swift Dzire VXi 1.2 BS IV',
       'Chevrolet Beat LT Diesel', 'BMW 7 Series 740Li Sedan',
       'Mahindra XUV500 W8 AWD 2013', 'Hyundai i10 Magna 1.2',
       'Hyundai Verna Fluidic New', 'Maruti Suzuki Swift VXi 1.2 BS IV',
       'Maruti Suzuki Ertiga ZXI Plus', 'Maruti Suzuki Ertiga Vxi',
       'Maruti Suzuki Ertiga VDi', 'Maruti Suzuki Alto LXi BS III',
       'Hyundai Grand i10 Asta 1.1 CRDi', 'Honda Amaze 1.2 S i VTEC',
       'Hyundai i20 Asta 1.4 CRDI 6 Speed', 'Ford Figo Diesel EXI',
       'Maruti Suzuki Eeco 5 STR WITH AC HTR', 'Maruti Suzuki Ertiga ZXi',
       'Maruti Suzuki Esteem LXi BS III', 'Maruti Suzuki Ritz VXI',
       'Maruti Suzuki Ritz LDi', 'Maruti Suzuki Dzire VDI',
       'Toyota Etios Liva G', 'Hyundai i20 Sportz 1.4 CRDI',
       'Chevrolet Spark', 'Nissan Micra XV', 'Maruti Suzuki Swift',
       'Honda Amaze 1.5 S i DTEC', 'Chevrolet Beat',
       'Honda City 1.5 V MT', 'Ford EcoSport Trend 1.5L TDCi',
       'Hyundai i20 Asta 1.2', 'Tata Indica V2 eLS',
       'Hindustan Motors Ambassador', 'Toyota Corolla Altis 1.8 GL',
       'Toyota Corolla Altis 1.8 J', 'Toyota Innova 2.5 GX BS IV 7 STR',
       'Volkswagen Jetta Highline TDI AT', 'Volkswagen Polo',
       'Mahindra Scorpio', 'Nissan Sunny', 'Hyundai Elite i20',
       'Renault Kwid', 'Mahindra Scorpio VLX Airbag',
       'Chevrolet Spark LT 1.0', 'Maruti Suzuki Swift RS VDI',
       'Fiat Punto Emotion 1.2', 'Hyundai i10 Sportz 1.2',
       'Chevrolet Beat LT Opt Diesel', 'Chevrolet Beat LS Diesel',
       'Tata Indigo CS', 'Maruti Suzuki Swift VDi',
       'Hyundai Eon Era Plus', 'Mahindra XUV500', 'Ford Fiesta',
       'Maruti Suzuki Wagon R', 'Hyundai i20',
       'Tata Indigo eCS LX TDI BS III',
       'Hyundai Fluidic Verna 1.6 CRDi SX', 'Fiat Petra ELX 1.2 PS',
       'Maruti Suzuki Zen VX', 'Hyundai Creta 1.6 SX Plus Petrol',
       'Mahindra Scorpio SLX', 'Toyota Innova 2.5 G BS III 8 STR',
       'Maruti Suzuki Wagon R LXI BS IV', 'Maruti Suzuki Alto Std BS IV',
       'Maruti Suzuki Wagon R LXi BS III',
       'Maruti Suzuki Swift VXI BSIII',
       'Tata Sumo Victa EX 10 by 7 Str BSIII',
       'Volkswagen Passat Diesel Comfortline AT',
       'Renault Scala RxL Diesel Travelogue',
       'Hyundai Grand i10 Sportz O 1.2 Kappa VTVT',
       'Hyundai i20 Active 1.2 SX', 'Mahindra Xylo E4',
       'Mahindra Bolero SLE BS IV', 'Maruti Suzuki SX4', 'Toyota Etios',
       'Honda City ZX VTEC', 'Maruti Suzuki Wagon R LX BS III',
       'Honda City VX O MT Diesel', 'Mahindra Thar CRDe 4x4 AC',
       'Audi A4 1.8 TFSI Multitronic Premium Plus',
       'Mercedes Benz GLA Class 200 CDI Sport',
       'Land Rover Freelander 2 SE', 'Tata Aria Pleasure 4X2',
       'Mercedes Benz B Class B180 Sports', 'Honda Jazz VX MT',
       'Hyundai i20 Active 1.4L SX O', 'Mini Cooper S',
       'Maruti Suzuki Ciaz ZXI Plus', 'Chevrolet Tavera Neo',
       'Hyundai Eon Sportz', 'Tata Sumo Gold Select Variant',
       'Maruti Suzuki Wagon R 1.0', 'Maruti Suzuki Esteem VXi BS III',
       'Chevrolet Enjoy 1.4 LS 8 STR', 'Maruti Suzuki Wagon R 1.0 VXi',
       'Nissan Terrano XL D Plus', 'Renault Duster 85 PS RxL Diesel',
       'Maruti Suzuki Dzire ZXI', 'Renault Kwid RXT Opt',
       'Maruti Suzuki Maruti 800 Std', 'Renault Kwid 1.0 RXT AMT',
       'Renault Scala RxL Diesel',
       'Hyundai Grand i10 Asta 1.2 Kappa VTVT O',
       'Chevrolet Beat LS Petrol', 'Hyundai Accent GLX',
       'Tata Indica V2 Xeta e GLE', 'Tata Indigo CS LS DiCOR',
       'Mahindra Scorpio VLX Special Edition BS III', 'Honda Accord',
       'Ford EcoSport Titanium 1.5 TDCi', 'Maruti Suzuki Ertiga',
       'Mahindra Scorpio 2.6 CRDe', 'Honda Mobilio',
       'Toyota Corolla Altis', 'Skoda Laura', 'Hyundai Verna Fluidic',
       'Maruti Suzuki Vitara Brezza', 'Tata Manza Aura Quadrajet',
       'Chevrolet Sail UVA Petrol LT ABS',
       'Hyundai Verna Fluidic 1.6 VTVT SX',
       'Audi A4 2.0 TDI 177bhp Premium', 'Hyundai Elantra SX',
       'Mahindra Scorpio VLX 4WD Airbag', 'Mahindra KUV100 K8 D 6 STR',
       'Hyundai i10', 'Hyundai i20 Active', 'Datsun Redi GO',
       'Toyota Etios Liva', 'Hyundai Accent', 'Hyundai Verna',
       'Toyota Fortuner', 'Hyundai i10 Sportz',
       'Chevrolet Spark LT 1.0 Airbag', 'Tata Indigo eCS VX CR4 BS IV',
       'Skoda Rapid Elegance 1.6 TDI CR MT', 'Tata Vista Quadrajet VX',
       'Maruti Suzuki Alto K10 VXi AT', 'Maruti Suzuki Zen LXi BS III',
       'Maruti Suzuki Swift Dzire Tour LDi', 'Honda City ZX EXi',
       'Chevrolet Beat Diesel', 'Hyundai Verna 1.4 VTVT',
       'Maruti Suzuki Maruti 800 Std – Befo',
       'Hyundai Elite i20 Asta 1.4 CRDI',
       'Maruti Suzuki Versa DX2 8 SEATER BSIII',
       'Tata Indigo LX TDI BS III',
       'Volkswagen Vento Konekt Diesel Highline',
       'Mercedes Benz C Class 200 CDI Classic', 'Hyundai Santro Xing GLS',
       'Maruti Suzuki Omni Limited Edition',
       'Hyundai Sonata Transform 2.4 GDi MT',
       'Maruti Suzuki Alto 800 Lxi', 'Honda Jazz S MT',
       'Hyundai Grand i10 Sportz 1.2 Kappa VTVT',
       'Maruti Suzuki Zen LXi BSII',
       'Mahindra Scorpio W Turbo 2.6DX 9 Seater',
       'Maruti Suzuki Alto K10 VXi',
       'Hyundai Grand i10 Asta 1.2 Kappa VTVT', 'Mahindra XUV500 W8',
       'Hyundai i20 Magna O 1.2', 'Renault Duster 85 PS RxL Explore LE',
       'Honda Brio V MT', 'Mahindra TUV300 T4 Plus',
       'Ford Ikon 1.3 CLXi NXt Finesse', 'Toyota Fortuner 3.0 4x4 MT',
       'Tata Manza ELAN Quadrajet',
       'Mercedes Benz A Class A 180 Sport Petrol', 'Tata Indigo LS',
       'Hyundai i20 Magna 1.2',
       'Volkswagen Vento Highline Plus 1.5 Diesel AT', 'Renault Kwid RXT',
       'Honda Amaze 1.5 E i DTEC', 'Hyundai Verna 1.6 EX VTVT',
       'BMW 5 Series 520d Sedan', 'Skoda Superb 1.8 TFSI AT',
       'Audi Q3 2.0 TDI quattro Premium', 'Mahindra Bolero DI BSII',
       'Ford Figo Duratorq Diesel Titanium 1.4',
       'Maruti Suzuki Wagon R VXI BS IV', 'Mahindra Logan Diesel 1.5 DLS',
       'Tata Nano GenX XMA', 'Ford Figo Petrol LXI',
       'Hyundai i10 Magna 1.2 Kappa2', 'Toyota Corolla H2',
       'Tata Indigo CS eLS BS IV', 'Hyundai Xcent Base 1.1 CRDi',
       'Hyundai Accent Executive Edition', 'Tata Zest XE 75 PS Diesel',
       'Maruti Suzuki Dzire LDI', 'Tata Sumo Gold LX BS IV',
       'Toyota Corolla Altis GL Petrol', 'Maruti Suzuki Eeco 7 STR',
       'Toyota Fortuner 3.0 4x2 MT', 'Mahindra XUV500 W6',
       'Maruti Suzuki 800', 'Honda Mobilio S i DTEC',
       'Hyundai Verna 1.6 CRDI E', 'Tata Indica', 'Hyundai Santro Xing',
       'Maruti Suzuki Zen Estilo', 'Honda Brio VX AT',
       'Maruti Suzuki Zen Estilo LXI Green CNG',
       'Maruti Suzuki Wagon R Select Variant', 'Hyundai Eon Magna Plus',
       'Maruti Suzuki Ritz GENUS VXI',
       'Hyundai Grand i10 Magna AT 1.2 Kappa VTVT',
       'Hyundai Eon D Lite Plus', 'Maruti Suzuki Estilo VXi ABS BS IV',
       'Maruti Suzuki Vitara Brezza LDi O', 'Mahindra Scorpio Vlx BSIV',
       'Mitsubishi Lancer 1.8 LXi', 'Maruti Suzuki Maruti 800 AC',
       'Maruti Suzuki Alto 800 LXI CNG O', 'Ford Fiesta SXi 1.6 ABS',
       'Maruti Suzuki Ritz VDi', 'Maruti Suzuki Estilo LX BS IV',
       'Audi A6 2.0 TDI Premium', 'Maruti Suzuki Alto',
       'Maruti Suzuki Baleno Sigma 1.2', 'Maruti Suzuki Swift GLAM',
       'Hyundai Getz Prime 1.3 GVS', 'Hyundai Santro',
       'Hyundai Getz Prime 1.3 GLX', 'Chevrolet Beat PS Diesel',
       'Ford EcoSport Trend 1.5 Ti VCT', 'Tata Indica V2 DLG',
       'BMW X1 xDrive20d xLine', 'Honda City 1.5 V AT',
       'Chevrolet Cruze LTZ AT', 'Maruti Suzuki Swift Dzire VDi',
       'Mahindra XUV500 W10', 'Maruti Suzuki Alto K10 LXi CNG',
       'Hyundai Accent GLE', 'Force Motors One SUV',
       'Chevrolet Spark 1.0 LT', 'Toyota Etios Liva GD',
       'Renault Duster 85PS Diesel RxL Optional with Nav',
       'Chevrolet Enjoy', 'BMW 5 Series 530i', 'Chevrolet Cruze LTZ',
       'Hyundai Verna VGT CRDi SX ABS', 'Maruti Suzuki Omni',
       'Maruti Suzuki Celerio VDi', 'Tata Zest Quadrajet 1.3',
       'Tata Indigo CS eLX BS IV', 'Hyundai i10 Era',
       'Tata Indigo eCS LX CR4 BS IV', 'Tata Indigo Marina LS',
       'Hyundai Xcent SX 1.2', 'Tata Nano LX Special Edition',
       'Renault Duster 110 PS RxZ Diesel',
       'Maruti Suzuki Wagon R AX BSIV', 'Mahindra Xylo E8',
       'Tata Manza Aqua Quadrajet', 'Tata Venture EX 8 STR',
       'Maruti Suzuki Swift Dzire Tour LXi',
       'Skoda Octavia Classic 1.9 TDI MT', 'Maruti Suzuki Omni LPG BS IV',
       'Tata Sumo Gold EX BS IV', 'Hyundai Verna 1.6 CRDI SX',
       'Mahindra Scorpio SLX 2.6 Turbo 8 Str',
       'Hyundai Elite i20 Sportz 1.2', 'Ford Ikon 1.6 Nxt',
       'Toyota Innova 2.5 V 7 STR', 'Nissan Sunny XL',
       'Maruti Suzuki Swift VDi BS IV', 'Toyota Innova 2.0 G4',
       'Maruti Suzuki Swift VDi ABS', 'Hyundai Elite i20 Asta 1.2',
       'Volkswagen Polo Trendline 1.5L D', 'Toyota Etios Liva Diesel',
       'Maruti Suzuki Ciaz ZXi Plus RS', 'Hyundai Elantra 1.8 S',
       'Ford EcoSport Trend 1.5L Ti VCT', 'Tata Indica eV2 LS',
       'Jaguar XF 2.2 Diesel Luxury',
       'Audi Q5 2.0 TDI quattro Premium Plus', 'BMW 3 Series 320d Sedan',
       'Maruti Suzuki Swift ZXi 1.2 BS IV', 'BMW X1 sDrive20d',
       'Maruti Suzuki S Cross Sigma 1.3', 'Maruti Suzuki Ertiga LDi',
       'Honda City SV', 'Volkswagen Vento Comfortline Petrol',
       'Mahindra KUV100', 'Maruti Suzuki Swift Dzire Tour VDi',
       'Mahindra Scorpio 2.6 SLX', 'Maruti Suzuki Omni 8 STR BS III',
       'Volkswagen Jetta Comfortline 1.9 TDI AT', 'Volvo S80 Summum D4',
       'Toyota Corolla Altis VL AT Petrol',
       'Mitsubishi Pajero Sport 2.5 AT', 'Chevrolet Beat LT Petrol',
       'BMW X1', 'Mercedes Benz C Class C 220 CDI Avantgarde',
       'Volkswagen Vento Comfortline Diesel', 'Tata Indigo CS GLS',
       'Honda City ZX GXi', 'Maruti Suzuki Wagon R Duo Lxi',
       'Maruti Suzuki Zen LX BSII', 'Renault Duster RxL Petrol',
       'Honda WR V S MT Petrol', 'Renault Duster 110 PS RxL Diesel',
       'Mahindra Scorpio LX BS III',
       'Maruti Suzuki SX4 Celebration Diesel',
       'Audi A3 Cabriolet 40 TFSI', 'Hyundai Santro AE GLS Audio',
       'Mahindra Xylo D2 BS IV', 'Hyundai Getz GLE',
       'Hyundai Santro Xing XL AT eRLX Euro III',
       'Hyundai Santro Xing XL eRLX Euro III',
       'Tata Indica V2 DLS BS III', 'Honda City 1.5 E MT',
       'Nissan Micra XL', 'Honda City 1.5 S Inspire',
       'Tata Indica eV2 eXeta eGLX', 'Maruti Suzuki Omni E 8 STR BS IV',
       'Maruti Suzuki Swift LDi', 'Hyundai Verna 1.6 CRDI SX Plus AT',
       'Chevrolet Tavera LS B3 10 Seats BSII',
       'Hindustan Motors Ambassador Classic Mark 4 – Befo',
       'Ford Fusion 1.4 TDCi Diesel',
       'Fiat Linea Emotion 1.4 L T Jet Petrol',
       'Ford Ikon 1.3 Flair Josh 100', 'Tata Indica V2 LS',
       'Mahindra Xylo D2', 'Toyota Corolla', 'Tata Sumo Grande MKII GX',
       'Volkswagen Polo Highline1.2L P', 'Tata Tiago Revotron XZ',
       'Tata Indigo eCS', 'Mahindra Xylo E8 BS IV',
       'Tata Sumo Gold FX BSIII', 'Hyundai Creta', 'Tata Bolt XM Petrol',
       'Maruti Suzuki Ritz', 'Hyundai i20 Asta',
       'Maruti Suzuki Swift Select Variant', 'Tata Indica V2 DLX BS III',
       'Mahindra Scorpio VLX 2.2 mHawk Airbag BSIV',
       'Toyota Innova 2.5 E 8 STR', 'Datsun Go Plus', 'Tata Indica V2',
       'Hyundai Santro Xing GL', 'Toyota Innova 2.5 Z Diesel 7 Seater',
       'Mahindra Logan', 'Maruti Suzuki 800 Std BS III',
       'Chevrolet Sail 1.2 LS', 'Tata Manza', 'Toyota Etios G',
       'Toyota Qualis', 'Mahindra Quanto C4', 'Maruti Suzuki Swift Dzire',
       'Hyundai i20 Select Variant', 'Honda City VX Petrol',
       'Hyundai Getz', 'Mercedes Benz C Class 200 K MT', 'Skoda Fabia',
       'Maruti Suzuki Ritz VXI ABS', 'Tata Indica V2 DLE BS III',
       'Tata Zest XM Diesel'], dtype=object)

In [26]:
for i in ds.index:
    company = ds.loc[i,"company"]
    name = ds.loc[i,"name"]
    name  = name.replace(company,"").strip() 
    ds.loc[i, "name"] = name # change in dataset
    print(name)

Santro Xing XO eRLX Euro III
Grand i10 Magna 1.2 Kappa VTVT
EcoSport Titanium 1.5L TDCi
Figo
Eon
EcoSport Ambiente 1.5L TDCi
Suzuki Alto K10 VXi AMT
Fabia Classic 1.2 MPI
Suzuki Stingray VXi
Elite i20 Magna 1.2
Scorpio SLE BS IV
Santro Xing XO eRLX Euro III
Q7
Scorpio S10
Suzuki Alto 800
Scorpio S10
Scorpio S10
Suzuki Alto 800 Vxi
i20 Sportz 1.2
i20 Sportz 1.2
i20 Sportz 1.2
Suzuki Alto 800 Lx
Suzuki Vitara Brezza ZDi
Suzuki Alto LX
Bolero DI
Suzuki Swift Dzire ZDi
Scorpio S10 4WD
Suzuki Swift Vdi BSIII
Suzuki Wagon R VXi BS III
Suzuki Wagon R VXi Minor
Innova 2.0 G 8 STR BS IV
Lodgy 85 PS RXL
Yeti Ambition 2.0 TDI CR 4x2
Suzuki Baleno Delta 1.2
Duster 110 PS RxZ Diesel Plus
Duster 85 PS RxE Diesel
City 1.5 S MT
Suzuki Alto K10 VXi AMT
Suzuki Dzire
Amaze
Amaze 1.5 SX i DTEC
City
Redi GO S
Suzuki SX4 ZXI MT
Pajero Sport Limited Edition
Bolero DI
Suzuki Swift Dzire ZDi
Scorpio S10 4WD
Suzuki Swift Vdi BSIII
Suzuki Wagon R VXi BS III
Suzuki Wagon R VXi Minor
Scorpio S10
Suzuki Swift VXi 1.2 ABS BS IV
City ZX CVT
Suzuki Wagon R LX BS IV
Figo
Eon
Indigo eCS LS CR4 BS IV
EcoSport Ambiente 1.5L TDCi
Indigo eCS LS CR4 BS IV
Scorpio SLE BS IV
Polo Highline Exquisite P
Fabia Classic 1.2 MPI
Suzuki Stingray VXi
Spark LS 1.0
Duster 110PS Diesel RxZ
City
Cooper S 1.6
Redi GO S
Fabia 1.2L Diesel Ambiente
Amaze
Amaze
Duster
Cooper S 1.6
Scorpio S4
Scorpio VLX 2WD BS IV
Quanto C8
EcoSport
Brio
i20 Magna
Corolla Altis Diesel D4DG
Verna Transform SX VTVT
Corolla Altis Petrol Ltd
City 1.5 EXi New
Elite i20 Magna 1.2
Fabia 1.2L Diesel Elegance
3 Series 320i
Suzuki A Star Lxi
Etios GD
Figo Diesel EXI Option
Suzuki Swift Dzire VXi 1.2 BS IV
Beat LT Diesel
7 Series 740Li Sedan
XUV500 W8 AWD 2013
i10 Magna 1.2
Verna Fluidic New
Suzuki Swift VXi 1.2 BS IV
Suzuki Ertiga ZXI Plus
EcoSport Titanium 1.5L TDCi
Suzuki Ertiga Vxi
Suzuki Ertiga VDi
Suzuki Alto LXi BS III
Grand i10 Asta 1.1 CRDi
Amaze 1.2 S i VTEC
i20 Asta 1.4 CRDI 6 Speed
Figo Diesel EXI
Suzuki Eeco 5 STR WITH AC HTR
Suzuki Ertiga ZXi
Suzuki Esteem LXi BS III
Suzuki Ritz VXI
Suzuki Dzire
Suzuki Ritz LDi
Suzuki Swift VXi 1.2 BS IV
Suzuki Dzire VDI
Etios Liva G
i20 Sportz 1.4 CRDI
Spark
Micra XV
Suzuki Swift
Amaze 1.5 S i DTEC
Suzuki Alto 800 Vxi
Beat
City 1.5 V MT
EcoSport Trend 1.5L TDCi
i20 Asta 1.2
Suzuki Swift Dzire VXi 1.2 BS IV
Indica V2 eLS
Motors Ambassador
Corolla Altis 1.8 GL
Corolla Altis 1.8 J
Innova 2.5 GX BS IV 7 STR
Jetta Highline TDI AT
Polo
Scorpio
Duster
Amaze
Sunny
Elite i20
Kwid
Duster
EcoSport
Duster
Scorpio VLX Airbag
Spark LT 1.0
Suzuki Swift RS VDI
Punto Emotion 1.2
Suzuki Swift RS VDI
Etios GD
i20 Sportz 1.4 CRDI
i10 Sportz 1.2
Beat LT Opt Diesel
Beat LS Diesel
Beat LT Diesel
Scorpio VLX 2WD BS IV
Indigo CS
Corolla Altis 1.8 J
City 1.5 V MT
Suzuki Swift VDi
Eon Era Plus
Scorpio S10
XUV500
Brio
Fiesta
Amaze
City
Suzuki Wagon R
City
i20
Indigo eCS LX TDI BS III
Fluidic Verna 1.6 CRDi SX
Quanto C8
Petra ELX 1.2 PS
Fabia 1.2L Diesel Ambiente
Cooper S 1.6
Suzuki Zen VX
City
Creta 1.6 SX Plus Petrol
Scorpio SLX
Scorpio SLE BS IV
Innova 2.5 G BS III 8 STR
Suzuki Alto K10 VXi AMT
Suzuki Wagon R LXI BS IV
Suzuki Alto Std BS IV
Suzuki Wagon R LXi BS III
Suzuki Swift VXI BSIII
Sumo Victa EX 10 by 7 Str BSIII
Suzuki Wagon R LXi BS III
Suzuki Alto LXi BS III
Passat Diesel Comfortline AT
Scala RxL Diesel Travelogue
Quanto C8
Grand i10 Sportz O 1.2 Kappa VTVT
i20 Active 1.2 SX
Xylo E4
Duster 110PS Diesel RxZ
Bolero SLE BS IV
Suzuki SX4
Etios
Polo
City ZX VTEC
Suzuki Wagon R LX BS III
City VX O MT Diesel
Thar CRDe 4x4 AC
Pajero Sport Limited Edition
A4 1.8 TFSI Multitronic Premium Plus
Benz GLA Class 200 CDI Sport
Rover Freelander 2 SE
Aria Pleasure 4X2
Benz B Class B180 Sports
Indigo eCS LX TDI BS III
Indigo eCS LX TDI BS III
Jazz VX MT
Amaze 1.2 S i VTEC
Amaze
City
City
Amaze
A4 1.8 TFSI Multitronic Premium Plus
Scorpio S4
i20 Active 1.4L SX O
Cooper S
Suzuki Ciaz ZXI Plus
Tavera Neo
Amaze
Eon Sportz
Sumo Gold Select Variant
Suzuki Wagon R 1.0
Suzuki Esteem VXi BS III
Enjoy 1.4 LS 8 STR
i20 Asta 1.4 CRDI 6 Speed
Figo Diesel EXI
Suzuki Eeco 5 STR WITH AC HTR
Suzuki Ertiga ZXi
Suzuki Esteem LXi BS III
Suzuki Ritz VXI
Suzuki Dzire
Suzuki Ritz LDi
Suzuki SX4 ZXI MT
Suzuki Wagon R 1.0 VXi
Cooper S 1.6
Terrano XL D Plus
Duster 85 PS RxE Diesel
Duster 85 PS RxE Diesel
Duster 85 PS RxL Diesel
Suzuki Dzire ZXI
Kwid RXT Opt
Suzuki  800 Std
Kwid 1.0 RXT AMT
Lodgy 85 PS RXL
Scala RxL Diesel
Grand i10 Asta 1.2 Kappa VTVT O
Suzuki Swift Dzire VXi 1.2 BS IV
Beat LS Petrol
Indigo eCS LX TDI BS III
Santro Xing XO eRLX Euro III
Fluidic Verna 1.6 CRDi SX
Beat LS Petrol
Quanto C8
Petra ELX 1.2 PS
Beat LS Petrol
Fabia 1.2L Diesel Ambiente
EcoSport Titanium 1.5L TDCi
Accent GLX
Cooper S 1.6
Cooper S 1.6
Indica V2 Xeta e GLE
Cooper S
Indigo CS LS DiCOR
Scorpio VLX Special Edition BS III
Accord
Scorpio S4
Tavera Neo
EcoSport Titanium 1.5 TDCi
Suzuki Ertiga
Amaze
Suzuki Dzire
City
Scorpio 2.6 CRDe
Suzuki Dzire
City
Mobilio
Corolla Altis
City
Laura
Duster
Suzuki Dzire
XUV500
Verna Fluidic
Suzuki Vitara Brezza
Suzuki Wagon R
Scorpio
Amaze
XUV500
Scorpio
Laura
Polo
Manza Aura Quadrajet
Sail UVA Petrol LT ABS
Duster 110 PS RxZ Diesel Plus
Verna Fluidic 1.6 VTVT SX
A4 2.0 TDI 177bhp Premium
Elantra SX
Scorpio VLX 4WD Airbag
KUV100 K8 D 6 STR
Scala RxL Diesel Travelogue
Quanto C8
Grand i10 Sportz O 1.2 Kappa VTVT
i20 Active 1.2 SX
Xylo E4
i20
Eon
i10
i20 Active
Redi GO
Etios Liva
Accent
Verna
Suzuki Swift
Fortuner
i10 Sportz
XUV500
Spark LT 1.0 Airbag
Duster 110PS Diesel RxZ
XUV500
Indigo eCS VX CR4 BS IV
Bolero SLE BS IV
Rapid Elegance 1.6 TDI CR MT
Vista Quadrajet VX
Suzuki Alto K10 VXi AT
Suzuki SX4
Suzuki Zen LXi BS III
i10 Magna 1.2
Suzuki Swift Dzire Tour LDi
City ZX EXi
Beat Diesel
City 1.5 S MT
Verna 1.4 VTVT
Suzuki  800 Std – Befo
Etios
Polo
Suzuki Swift
Elite i20 Asta 1.4 CRDI
Suzuki Swift Dzire VXi 1.2 BS IV
Suzuki Versa DX2 8 SEATER BSIII
Indigo LX TDI BS III
Vento Konekt Diesel Highline
Benz C Class 200 CDI Classic
Suzuki Ertiga VDi
City
Santro Xing GLS
Suzuki Omni Limited Edition
Sonata Transform 2.4 GDi MT
Vento Konekt Diesel Highline
Suzuki Alto 800 Lxi
Suzuki Alto LXi BS III
Jazz S MT
Grand i10 Sportz 1.2 Kappa VTVT
Suzuki Zen LXi BSII
Scorpio W Turbo 2.6DX 9 Seater
Suzuki Alto K10 VXi
Grand i10 Asta 1.2 Kappa VTVT
XUV500 W8
Creta 1.6 SX Plus Petrol
i20 Magna O 1.2
Duster 85 PS RxL Explore LE
Grand i10 Sportz 1.2 Kappa VTVT
Brio V MT
TUV300 T4 Plus
Spark LS 1.0
Suzuki Swift Dzire Tour LDi
Ikon 1.3 CLXi NXt Finesse
Fortuner 3.0 4x4 MT
Manza ELAN Quadrajet
Benz A Class A 180 Sport Petrol
Beat LS Diesel
EcoSport Trend 1.5L TDCi
Indigo LS
i20 Magna 1.2
Vento Highline Plus 1.5 Diesel AT
Kwid RXT
EcoSport Titanium 1.5L TDCi
Amaze 1.5 E i DTEC
Verna 1.6 EX VTVT
5 Series 520d Sedan
Superb 1.8 TFSI AT
Q3 2.0 TDI quattro Premium
Bolero DI BSII
Scorpio S10
Figo Duratorq Diesel Titanium 1.4
Suzuki Wagon R VXI BS IV
Logan Diesel 1.5 DLS
Nano GenX XMA
TUV300 T4 Plus
TUV300 T4 Plus
Elite i20 Magna 1.2
Elite i20 Magna 1.2
Suzuki Baleno Delta 1.2
Figo Petrol LXI
Scorpio S10
Elite i20 Magna 1.2
Suzuki Versa DX2 8 SEATER BSIII
Pajero Sport Limited Edition
i10 Magna 1.2 Kappa2
Corolla H2
Indigo CS eLS BS IV
Scorpio S10
Scorpio S10
Xcent Base 1.1 CRDi
City
Accent Executive Edition
Suzuki Baleno Delta 1.2
Zest XE 75 PS Diesel
Suzuki Dzire LDI
Sumo Gold LX BS IV
Corolla Altis GL Petrol
Suzuki Eeco 7 STR
Fortuner 3.0 4x2 MT
XUV500 W6
Suzuki 800
Suzuki Ertiga Vxi
Suzuki Versa DX2 8 SEATER BSIII
Mobilio S i DTEC
Suzuki Ertiga
Suzuki Vitara Brezza
Verna 1.6 CRDI E
Suzuki Swift VXI BSIII
Fortuner 3.0 4x2 MT
Amaze
Indica
Santro Xing
Suzuki Zen Estilo
Suzuki Wagon R LXI BS IV
Brio VX AT
Suzuki Zen LXi BSII
Suzuki Zen Estilo LXI Green CNG
Suzuki Wagon R Select Variant
Suzuki Alto LXi BS III
Eon Magna Plus
City 1.5 S MT
Motors Ambassador
Suzuki Ritz GENUS VXI
Grand i10 Magna AT 1.2 Kappa VTVT
Eon D Lite Plus
Suzuki Swift Dzire VXi 1.2 BS IV
Suzuki Wagon R VXI BS IV
Suzuki Estilo VXi ABS BS IV
Suzuki Vitara Brezza LDi O
Suzuki Eeco 5 STR WITH AC HTR
Scorpio Vlx BSIV
Suzuki Ertiga VDi
Lancer 1.8 LXi
Suzuki  800 AC
Suzuki Alto 800 LXI CNG O
Grand i10 Magna 1.2 Kappa VTVT
Eon D Lite Plus
Fiesta SXi 1.6 ABS
Suzuki Ritz VDi
Verna Fluidic New
Suzuki Wagon R LXi BS III
Suzuki Estilo LX BS IV
A6 2.0 TDI Premium
Suzuki Wagon R LXi BS III
Suzuki Wagon R
Suzuki Wagon R
Suzuki Alto
Suzuki Baleno Sigma 1.2
Suzuki Swift GLAM
Getz Prime 1.3 GVS
Santro
Getz Prime 1.3 GLX
Beat PS Diesel
EcoSport Trend 1.5 Ti VCT
Suzuki Dzire ZXI
Fluidic Verna 1.6 CRDi SX
Indica V2 DLG
X1 xDrive20d xLine
i20 Asta 1.2
City 1.5 V AT
Cruze LTZ AT
Verna Fluidic New
Suzuki Swift Dzire VDi
XUV500 W6
XUV500 W10
Suzuki Alto K10 LXi CNG
Accent GLE
Motors One SUV
Spark 1.0 LT
i10
Etios Liva GD
Duster 85PS Diesel RxL Optional with Nav
Enjoy
5 Series 530i
Etios Liva G
Beat LS Diesel
Cruze LTZ
Suzuki Ertiga VDi
Verna VGT CRDi SX ABS
Suzuki Omni
Suzuki Celerio VDi
Zest Quadrajet 1.3
XUV500 W6
Indigo CS eLX BS IV
i10 Era
Indigo eCS LX TDI BS III
Indigo LX TDI BS III
Indigo eCS LX CR4 BS IV
Indigo Marina LS
Xcent SX 1.2
Eon Magna Plus
Duster 85 PS RxL Diesel
Suzuki Alto K10 LXi CNG
Nano LX Special Edition
Duster 110 PS RxZ Diesel
Suzuki Wagon R AX BSIV
Suzuki Swift
Suzuki Ertiga
Suzuki Swift VXi 1.2 ABS BS IV
i20 Magna
i10 Magna 1.2
Zest XE 75 PS Diesel
Xylo E8
Corolla Altis GL Petrol
Manza Aqua Quadrajet
Venture EX 8 STR
Suzuki Swift Dzire Tour LXi
Octavia Classic 1.9 TDI MT
Suzuki Omni LPG BS IV
Beat Diesel
Sumo Gold EX BS IV
Verna 1.6 CRDI SX
Sumo Gold EX BS IV
Scorpio 2.6 CRDe
Suzuki Zen LXi BS III
Suzuki Swift Dzire VXi 1.2 BS IV
Scorpio SLX 2.6 Turbo 8 Str
Grand i10 Sportz 1.2 Kappa VTVT
Elite i20 Sportz 1.2
Ikon 1.6 Nxt
Innova 2.5 V 7 STR
Sunny XL
Beat LT Diesel
Suzuki Alto 800 Lxi
Suzuki Swift VDi BS IV
Suzuki Swift VDi BS IV
Suzuki Swift
Innova 2.0 G4
Suzuki Swift VDi ABS
Elite i20 Asta 1.2
XUV500 W10
Polo Trendline 1.5L D
Etios Liva Diesel
TUV300 T4 Plus
Elite i20 Asta 1.2
Santro Xing GLS
Suzuki Zen LXi BS III
Suzuki Ciaz ZXi Plus RS
Eon Era Plus
Elantra 1.8 S
Suzuki Swift VDi
Suzuki Zen Estilo LXI Green CNG
Eon Era Plus
Grand i10 Magna 1.2 Kappa VTVT
Verna Fluidic New
EcoSport Trend 1.5L Ti VCT
i20 Magna
Beat Diesel
Indica eV2 LS
XF 2.2 Diesel Luxury
Q5 2.0 TDI quattro Premium Plus
3 Series 320d Sedan
Suzuki Swift ZXi 1.2 BS IV
X1 sDrive20d
Suzuki S Cross Sigma 1.3
Suzuki Ertiga LDi
Suzuki Alto K10 VXi AMT
City SV
Vento Comfortline Petrol
City 1.5 EXi New
A4 2.0 TDI 177bhp Premium
KUV100
Zest XE 75 PS Diesel
XUV500 W8
Suzuki Swift Dzire Tour VDi
Sumo Gold LX BS IV
Suzuki Swift Dzire VXi 1.2 BS IV
Scorpio 2.6 SLX
Suzuki Omni 8 STR BS III
Pajero Sport Limited Edition
Jetta Comfortline 1.9 TDI AT
Suzuki Ertiga Vxi
A4 2.0 TDI 177bhp Premium
S80 Summum D4
Corolla Altis VL AT Petrol
Pajero Sport 2.5 AT
Beat LT Petrol
X1
Benz C Class C 220 CDI Avantgarde
Scorpio SLX
Vento Comfortline Diesel
Indigo CS GLS
City ZX GXi
Suzuki Wagon R Duo Lxi
EcoSport Trend 1.5L TDCi
Suzuki Swift Dzire VDi
Suzuki Omni 8 STR BS III
Suzuki Zen LX BSII
Duster RxL Petrol
Suzuki Swift VXi 1.2 BS IV
WR V S MT Petrol
Indigo CS eLX BS IV
Duster 110 PS RxL Diesel
Scorpio LX BS III
Suzuki Zen LXi BS III
Suzuki Wagon R LXi BS III
Suzuki SX4 Celebration Diesel
A3 Cabriolet 40 TFSI
Eon D Lite Plus
Scorpio SLX
Santro AE GLS Audio
Suzuki Swift Dzire Tour VDi
Scorpio S4
Xylo D2 BS IV
Santro
Beat LT Diesel
Suzuki Swift Dzire VDi
XUV500 W8
Fortuner 3.0 4x4 MT
Suzuki Alto K10 VXi
Getz GLE
Suzuki Swift Dzire Tour LDi
Santro Xing XL AT eRLX Euro III
Santro Xing XL eRLX Euro III
Xylo D2 BS IV
Santro Xing XL eRLX Euro III
Indica V2 DLS BS III
i10 Sportz 1.2
Santro Xing XL AT eRLX Euro III
City 1.5 E MT
Micra XL
City 1.5 S Inspire
Suzuki Alto 800 Lxi
Suzuki Wagon R LX BS III
Suzuki Ertiga VDi
Indica eV2 eXeta eGLX
Suzuki Omni E 8 STR BS IV
Eon Era Plus
Eon
Suzuki Swift LDi
Verna 1.6 CRDI SX Plus AT
Tavera LS B3 10 Seats BSII
Suzuki Zen LXi BS III
EcoSport Titanium 1.5 TDCi
Motors Ambassador Classic Mark 4 – Befo
Fusion 1.4 TDCi Diesel
Santro Xing XL AT eRLX Euro III
Santro
Linea Emotion 1.4 L T Jet Petrol
Ikon 1.3 Flair Josh 100
Indica V2 LS
Scorpio S4
Santro Xing XL eRLX Euro III
Xylo D2
Grand i10 Asta 1.2 Kappa VTVT
Suzuki Alto 800 Lxi
Corolla
Sumo Grande MKII GX
Suzuki Swift VDi
Polo Highline1.2L P
Suzuki Alto 800 Lx
Tiago Revotron XZ
Suzuki Swift LDi
Suzuki Swift VDi
Indigo eCS
Beat LS Diesel
Xylo E8 BS IV
Eon D Lite Plus
Sumo Gold FX BSIII
Elite i20
i10 Magna 1.2 Kappa2
Creta
Polo
Suzuki Dzire
Bolt XM Petrol
Suzuki Alto 800 Lx
Suzuki Alto
Suzuki Ritz
Suzuki Alto 800 Lxi
Suzuki Dzire
i20 Asta
Suzuki Swift Select Variant
Indica V2 DLX BS III
Scorpio VLX 2.2 mHawk Airbag BSIV
Innova 2.5 E 8 STR
Xylo E8
i20 Magna 1.2
Suzuki Omni
KUV100
Go Plus
Indica V2
Santro Xing GL
Suzuki Wagon R 1.0 VXi
Suzuki Swift Select Variant
Innova 2.5 Z Diesel 7 Seater
Polo Highline1.2L P
Logan
Suzuki 800 Std BS III
Scorpio
Sail 1.2 LS
Santro AE GLS Audio
Eon
Manza
Etios G
Getz Prime 1.3 GLX
Qualis
Santro Xing
Indica eV2 LS
City 1.5 S MT
Zest XE 75 PS Diesel
Quanto C4
Indigo eCS LX CR4 BS IV
Suzuki Swift Dzire
Elite i20
i20 Select Variant
Tavera Neo
Suzuki Dzire
City VX Petrol
Getz
Benz C Class 200 K MT
Suzuki Alto LXi BS III
Suzuki Swift Dzire Tour VDi
Fabia
Suzuki Ritz VXI ABS
Indica V2 DLE BS III
Corolla Altis
Zest XM Diesel
Quanto C8

In [27]:
ds.duplicated().unique()

array([False,  True])

In [28]:
ds.drop_duplicates(inplace = True)

In [29]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 651 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        651 non-null    object
 1   company     651 non-null    object
 2   year        651 non-null    int32
 3   Price       651 non-null    float64
 4   kms_driven  651 non-null    int64
 5   fuel_type   651 non-null    object
dtypes: float64(1), int32(1), int64(1), object(3)
memory usage: 33.1+ KB

In [30]:
#used to reset the index back to default integer index
ds.reset_index(inplace=True)

In [31]:
ds.to_csv("cleaned_car_data.csv")